In [25]:
import numpy as np
import pandas as pd

In [57]:
#read datasets
train_txn = pd.read_csv('../final_txn_v2.csv')
train_user = pd.read_csv('../final_user_log_v2.csv')
train = train_txn.merge(train_user, on='new_id', how='inner')
train.head()

,new_id,payment_plan_days,plan_list_price,actual_amount_paid,avg_daily_paid,list_actual_diff,mean_ar,stopped_ar,mean_cancel,last_cancel,...,months_listening,listening_p6,listening_p12,logavg_secs_p12,freq_days,std_logsecs,total_entries,cluster9,freq_days_mean,ul_tenure
0,988305,60.0,298.0,894.0,14.900000,-596.0,0.833333,True,0.166667,0.0,...,7-12,1.0,1.0,8.738223,0.5,1.852721,64.0,3.0,0.086538,728.0
1,723425,127.0,627.0,627.0,4.937008,0.0,0.000000,False,0.000000,0.0,...,7-12,1.0,6.0,10.306972,1.0,1.145499,80.0,7.0,0.110181,717.0
2,1066360,540.0,2682.0,2682.0,4.966667,0.0,0.000000,False,0.000000,0.0,...,19-24,6.0,12.0,11.288232,1.0,1.415583,342.0,5.0,0.577966,590.0
3,180122,787.0,3874.0,4172.0,5.301144,-298.0,0.965517,True,0.103448,0.0,...,0-6,0.0,0.0,-0.618040,0.0,0.000000,0.0,9.0,0.000000,0.0
4,372093,840.0,3222.0,3649.0,4.344048,-427.0,1.000000,False,0.096774,0.0,...,25-27,6.0,12.0,10.571583,1.0,1.205211,271.0,1.0,0.329268,820.0

In [58]:
train.shape

(970960, 33)

In [59]:
loc = train.columns.get_loc('is_churn')
loc

21

In [60]:
train_np = train.values
train_yes = train_np[train_np[:,loc] == 1, :]
train_no = train_np[train_np[:,loc] == 0, :]
print(train_yes.shape)
print(train_no.shape)

(87328, 33)
(883632, 33)

In [70]:
ntrain_yes = train_yes.repeat(10, axis = 0)
ntrain_yes.shape
#new_train = np.concatenate(ntrain_yes, train_no)

(873280, 33)

In [62]:
l1 = ntrain_yes.tolist() + train_no.tolist()
t_cols = train.columns
ntrain = pd.DataFrame(l1, columns = t_cols)

In [48]:
ntrain.head()

,new_id,payment_plan_days,plan_list_price,actual_amount_paid,avg_daily_paid,list_actual_diff,mean_ar,stopped_ar,mean_cancel,last_cancel,...,months_listening,listening_p6,listening_p12,logavg_secs_p12,freq_days,std_logsecs,total_entries,cluster9,freq_days_mean,ul_tenure
0,988305,60.0,298.0,894.0,14.9,-596.0,0.833333,True,0.166667,0.0,...,7-12,1.0,1.0,8.738223,0.5,1.852721,64.0,3.0,0.086538,728.0
1,988305,60.0,298.0,894.0,14.9,-596.0,0.833333,True,0.166667,0.0,...,7-12,1.0,1.0,8.738223,0.5,1.852721,64.0,3.0,0.086538,728.0
2,988305,60.0,298.0,894.0,14.9,-596.0,0.833333,True,0.166667,0.0,...,7-12,1.0,1.0,8.738223,0.5,1.852721,64.0,3.0,0.086538,728.0
3,988305,60.0,298.0,894.0,14.9,-596.0,0.833333,True,0.166667,0.0,...,7-12,1.0,1.0,8.738223,0.5,1.852721,64.0,3.0,0.086538,728.0
4,988305,60.0,298.0,894.0,14.9,-596.0,0.833333,True,0.166667,0.0,...,7-12,1.0,1.0,8.738223,0.5,1.852721,64.0,3.0,0.086538,728.0

In [32]:
cols = ntrain.columns

for col in cols:
    print ('%s:\t\t\t %s Nulls' %(col ,len(ntrain[pd.isnull(ntrain[col]) == True])))

new_id:			 0 Nulls
payment_plan_days:			 0 Nulls
plan_list_price:			 0 Nulls
actual_amount_paid:			 0 Nulls
avg_daily_paid:			 0 Nulls
list_actual_diff:			 0 Nulls
mean_ar:			 0 Nulls
stopped_ar:			 0 Nulls
mean_cancel:			 0 Nulls
last_cancel:			 0 Nulls
lst_free_trial:			 0 Nulls
per_free_trial:			 0 Nulls
per_days_free_trial:			 0 Nulls
txn_cnt:			 0 Nulls
per_lp_high:			 0 Nulls
prev_churn_per:			 0 Nulls
pmt_change_cnt:			 0 Nulls
not_equal:			 0 Nulls
lst_memb_expire_post:			 0 Nulls
memb_tenure_days:			 0 Nulls
lst_memb_expire_days:			 0 Nulls
is_churn:			 0 Nulls
no_songs_cp6:			 0 Nulls
months_listening:			 0 Nulls
listening_p6:			 0 Nulls
listening_p12:			 0 Nulls
logavg_secs_p12:			 0 Nulls
freq_days:			 0 Nulls
std_logsecs:			 0 Nulls
total_entries:			 0 Nulls
cluster9:			 0 Nulls
freq_days_mean:			 0 Nulls
ul_tenure:			 0 Nulls

In [63]:
#x = get_dummies(ntrain['months_listening'], prefix='m_')

ntrain = ntrain.join(pd.get_dummies(ntrain['months_listening'])).drop('months_listening', axis =1)
ntrain.columns

Index(['new_id', 'payment_plan_days', 'plan_list_price', 'actual_amount_paid',
       'avg_daily_paid', 'list_actual_diff', 'mean_ar', 'stopped_ar',
       'mean_cancel', 'last_cancel', 'lst_free_trial', 'per_free_trial',
       'per_days_free_trial', 'txn_cnt', 'per_lp_high', 'prev_churn_per',
       'pmt_change_cnt', 'not_equal', 'lst_memb_expire_post',
       'memb_tenure_days', 'lst_memb_expire_days', 'is_churn', 'no_songs_cp6',
       'listening_p6', 'listening_p12', 'logavg_secs_p12', 'freq_days',
       'std_logsecs', 'total_entries', 'cluster9', 'freq_days_mean',
       'ul_tenure', 'm__0-6', 'm__13-18', 'm__19-24', 'm__25-27', 'm__7-12'],
      dtype='object')

In [65]:
ntrain = ntrain.join(pd.get_dummies(ntrain['cluster9'], prefix = 'cluster')).drop('cluster9', axis =1)
ntrain.columns

Index(['new_id', 'payment_plan_days', 'plan_list_price', 'actual_amount_paid',
       'avg_daily_paid', 'list_actual_diff', 'mean_ar', 'stopped_ar',
       'mean_cancel', 'last_cancel', 'lst_free_trial', 'per_free_trial',
       'per_days_free_trial', 'txn_cnt', 'per_lp_high', 'prev_churn_per',
       'pmt_change_cnt', 'not_equal', 'lst_memb_expire_post',
       'memb_tenure_days', 'lst_memb_expire_days', 'is_churn', 'no_songs_cp6',
       'listening_p6', 'listening_p12', 'logavg_secs_p12', 'freq_days',
       'std_logsecs', 'total_entries', 'freq_days_mean', 'ul_tenure', 'm__0-6',
       'm__13-18', 'm__19-24', 'm__25-27', 'm__7-12', 'cluster_0.0',
       'cluster_1.0', 'cluster_2.0', 'cluster_3.0', 'cluster_4.0',
       'cluster_5.0', 'cluster_6.0', 'cluster_7.0', 'cluster_8.0',
       'cluster_9.0'],
      dtype='object')

In [90]:
#print(ntrain[(pd.isnull(ntrain['listening_p6']) == True)]['new_id'].nunique())
#ntrain[(pd.isnull(ntrain['payment_plan_days']) == True) & (ntrain['is_churn_x'] == 0)]['new_id'].nunique()
#ntrain[(pd.isnull(ntrain['payment_plan_days']) == True) & (pd.isnull(ntrain['months_listening'] == True))]['new_id'].nunique()

123005

1434

In [90]:
train = train.join(pd.get_dummies(train['months_listening'])).drop('months_listening', axis =1)
train.columns
train = train.join(pd.get_dummies(train['cluster9'], prefix = 'cluster')).drop('cluster9', axis =1)
train.columns

Index(['new_id', 'payment_plan_days', 'plan_list_price', 'actual_amount_paid',
       'avg_daily_paid', 'list_actual_diff', 'mean_ar', 'stopped_ar',
       'mean_cancel', 'last_cancel', 'lst_free_trial', 'per_free_trial',
       'per_days_free_trial', 'txn_cnt', 'per_lp_high', 'prev_churn_per',
       'pmt_change_cnt', 'not_equal', 'lst_memb_expire_post',
       'memb_tenure_days', 'lst_memb_expire_days', 'is_churn', 'no_songs_cp6',
       'listening_p6', 'listening_p12', 'logavg_secs_p12', 'freq_days',
       'std_logsecs', 'total_entries', 'freq_days_mean', 'ul_tenure', '0-6',
       '13-18', '19-24', '25-27', '7-12', 'cluster_0.0', 'cluster_1.0',
       'cluster_2.0', 'cluster_3.0', 'cluster_4.0', 'cluster_5.0',
       'cluster_6.0', 'cluster_7.0', 'cluster_8.0', 'cluster_9.0'],
      dtype='object')

In [97]:
y = train['is_churn']
X = train.drop('is_churn', axis = 1)

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, log_loss

depthss = []
loglosss = []
for depth in range(7,27):
    depthss.append(depth)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 1)

    y_train = y_train.reshape(len(y_train), 1)
    y_test = y_test.reshape(len(y_test), 1)

    #print(y_train.shape)
    #print(y_test.shape)
    #print(X_train.shape)
    #print(X_test.shape)

    # Fitting Decision Tree Classification to the Training set
    classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0, max_depth = depth)
    classifier.fit(X_train, y_train)

    # Predicting the Test set results
    y_pred = classifier.predict(X_test)

    # Making the Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    
    #logloss
    print(log_loss(y_test, y_pred))
    loglosss.append(log_loss(y_test, y_pred))
    #print ('Error: {:0.2f}%' .format(((cm[0][1]+ cm[1][0])/(cm[1][1]+ cm[0][0]))*100))
    

plt.plot(depthss, loglosss)

C:\Users\Cathy\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
C:\Users\Cathy\Anaconda3\lib\site-packages\ipykernel\__main__.py:11: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead

1.94667528377
1.88015622229
1.82573132749
1.76383667987
1.72328505551
1.71207889043
1.69696110177
1.7085224782

In [24]:
ntrain.describe()

,is_churn_x,new_id,payment_plan_days,plan_list_price,actual_amount_paid,avg_daily_paid,list_actual_diff,mean_ar,mean_cancel,last_cancel,...,no_songs_cp6,listening_p6,listening_p12,logavg_secs_p12,freq_days,std_logsecs,total_entries,cluster9,freq_days_mean,ul_tenure
count,1.756930e+06,1.756930e+06,1.756930e+06,1.756930e+06,1.756930e+06,1.756930e+06,1.756930e+06,1.756930e+06,1.756930e+06,1.756930e+06,...,1.756930e+06,1.756930e+06,1.756930e+06,1.756930e+06,1.756930e+06,1.756930e+06,1.756930e+06,1.756930e+06,1.756930e+06,1.756930e+06
mean,4.970602e-01,5.381077e+05,4.585838e+02,2.071866e+03,2.128011e+03,inf,-5.614537e+01,6.980272e-01,2.517196e-02,4.462158e-02,...,1.010050e+00,4.323873e+00,7.950455e+00,9.507750e+00,7.696371e-01,1.063891e+00,2.622541e+02,3.559182e+00,4.749884e-01,4.778157e+02
std,4.999915e-01,3.107577e+05,2.532733e+02,1.243181e+03,1.294577e+03,NaN,1.950570e+02,4.402613e-01,9.071168e-02,2.064716e-01,...,2.162359e+00,2.329865e+00,4.674091e+00,4.042883e+00,3.716525e-01,4.625534e-01,2.358545e+02,2.948119e+00,3.100103e-01,3.104393e+02
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-2.086000e+03,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,-6.180397e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,0.000000e+00,2.690028e+05,2.470000e+02,1.043000e+03,1.043000e+03,3.333333e+00,-5.900000e+01,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,2.000000e+00,3.000000e+00,9.602545e+00,5.000000e-01,9.475266e-01,4.700000e+01,1.000000e+00,2.003318e-01,1.820000e+02
50%,0.000000e+00,5.376540e+05,4.800000e+02,1.881000e+03,1.881000e+03,4.810714e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,6.000000e+00,1.100000e+01,1.100962e+01,1.000000e+00,1.134695e+00,2.020000e+02,3.000000e+00,4.937811e-01,5.060000e+02
75%,1.000000e+00,8.070660e+05,6.600000e+02,3.129000e+03,3.278000e+03,5.146082e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,6.000000e+00,1.200000e+01,1.181004e+01,1.000000e+00,1.307129e+00,4.350000e+02,6.000000e+00,7.448630e-01,8.110000e+02
max,1.000000e+00,1.076940e+06,2.852000e+03,1.680000e+04,1.680000e+04,inf,1.599000e+03,1.000000e+00,1.000000e+00,1.000000e+00,...,6.000000e+00,6.000000e+00,1.200000e+01,1.418013e+01,1.000000e+00,6.924236e+00,8.210000e+02,9.000000e+00,1.000000e+00,8.200000e+02